### PR TITLE
RAMP

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
Motivation: make the kit RAMP-compatible.

Before merging, check that `ramp-test-submission` works properly.

### CODE REVIEW

**Comment by GuillaumeDesforges** [comment]
The problem.py has not been tested yet.

The `submission/starting_kit` submission has not been done yet.

**Comment by GuillaumeDesforges** [comment]
TODO: test with `ramp-test-submissions`

**Comment by avouacr** [comment]
The `submission/starting_kit` works with `ramp-test-submissions`.

**Comment by GuillaumeDesforges** [comment]
Some __pycache__ folders have been commited unfortunately.

**Comment by avouacr** [comment]
Oops, my bad.. je vire ça.

**Pull request merged**
